name: Continuous Deployment

on:
  push:
    branches:
      - main  # Trigger deployment only when code is merged to `main`

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Debug DOCKER_USERNAME
        run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_github
          chmod 600 ~/.ssh/id_rsa_github

      - name: Deploy using SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_github ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
          docker stop fastapi-app || true
          docker rm fastapi-app || true
          docker run -d --name fastapi-app -p 8000:8000 --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
          EOF
